export const TOPIC_POOL = [
  "How to file a public records request in Iowa",
  "Iowa journalist career paths and salary guide",
  "Understanding Iowa reporter shield privilege in court",
  "Best practices for covering Iowa state legislature sessions",
  "Local news sustainability in rural Iowa communities",
  "Investigative journalism resources for Iowa reporters",
  "How to build reliable sources in small-town Iowa",
  "Covering Iowa caucuses as a local journalist",
  "Ethics guide for Iowa newsrooms and freelancers",
  "Student journalism opportunities at Iowa universities",
  "How Iowa Freedom of Information Council helps reporters",
  "Covering Iowa agriculture and farm policy for local media",
  "Tips for Iowa broadcast journalists covering breaking news",
  "How to pitch investigative stories to Iowa editors",
  "Open meetings law basics for Iowa journalists",
  "Building a freelance journalism career in Des Moines",
  "Covering Iowa school boards and education policy",
  "Digital tools Iowa journalists should know in 2026",
  "How to verify sources and fight misinformation in Iowa",
  "Covering Iowa courts and criminal justice as a reporter",
  "Networking for journalists at Iowa media associations",
  "Writing compelling local feature stories in Iowa",
  "How Iowa nonprofit newsrooms are filling coverage gaps",
  "Safety tips for Iowa reporters at public protests",
  "Creating a portfolio for Iowa journalism job applications",
  "Covering Iowa city council meetings effectively",
  "How to use Iowa court records in investigative reporting",
  "Reporting on Iowa healthcare and Medicaid policy",
  "Covering Iowa environmental issues and water quality",
  "Guide to Iowa election coverage for local reporters",
  "How to interview Iowa state officials professionally",
  "Covering Iowa Native American communities with respect",
  "Reporting on Iowa housing affordability and zoning",
  "How Iowa weekly newspapers stay relevant in 2026",
  "Covering Iowa high school sports beyond the scoreboard",
  "Data journalism starter guide for Iowa reporters",
  "How to cover Iowa weather disasters and recovery",
  "Reporting Iowa business and economic development",
  "Covering Iowa arts and culture for local audiences",
  "How to write effective Iowa opinion columns",
  "Mobile journalism tips for Iowa field reporters",
  "Covering Iowa veterans issues and VA resources",
  "How to navigate Iowa libel law as a journalist",
  "Reporting on Iowa public transit and infrastructure",
  "Covering Iowa mental health policy and access",
  "How to build an email newsletter for Iowa readers",
  "Podcasting guide for Iowa local news outlets",
  "Covering Iowa immigration stories with accuracy",
  "How Iowa journalists can use social media responsibly",
  "Reporting Iowa energy policy and renewable projects",
];

export function pickTopicFromPool(exclude: string[] = []): string {
  const available = TOPIC_POOL.filter((t) => !exclude.includes(t));
  const pool = available.length > 0 ? available : TOPIC_POOL;
  return pool[Math.floor(Math.random() * pool.length)];
}
